### PR TITLE
🐠 Add syntax group that matches a list item checkbox `mkdListItemCheckbox`

### PR DESCRIPTION
**Pull request by patstockwell**
# 🐋 What
- Add new syntax match group `mkdListItemCheckbox`
- Add the new syntax group to `nextgroup` in `mkdListItem`
- Add the new syntax group to `contains` in `mkdListItemLine`

# 🦑 Why
- To allow highlighting checkboxes!

# 🐡 How
- Use the `nextgroup` keyword to ensure that checkboxes are only searched for matches following a `mkdListItem`
- Create a new group rather than extending an existing group so that highlighting is not forced on existing users, but they can opt in to use it.
- This change supports 4 "filled" checkbox styles. The most common in use is the lowercase `[x]`. Uppercase `[X]` is also valid (e.g. _GitHub_ accepts both). The `[o]` or `[O]` is sometimes used to represent incomplete subtask lists (For example _Vimwiki_ uses this markdown syntax) . e.g.
  ```markdown
  - [o] Christmas shopping
    - [x] Buy for mum
    - [ ] Buy for brother
    - [ ] Buy for wife
  ```

# 🐟 Screenshots

**Before**
Screen Shot 2021-12-04 at 1 40 52 pm

**After with highlight targeting the new syntax group `mkdListItemCheckbox`**
Screen Shot 2021-12-04 at 1 42 07 pm

# 🐢 GIF

### CODE REVIEW

**Comment by patstockwell** [comment]
Hi @alerque I've seen you comment and approve a few recent PRs, just wondering if you would take a look at this one if you have some time. Thank you! 🙏

**Review by alerque — DISMISSED** [review]
Looks pretty good to me. Lets see what CI has to say. I just merged master into this just our new CI workflows to life.

**Review by alerque — COMMENTED** [review]
Should we link this to some existing group by default?

**Comment by patstockwell** [comment]
Thanks @alerque, I've linked the new `mkdListItemCheckbox` group to the `Identifier` highlight group. I also indented existing highlight groups which makes for a bit of a noisy diff (the new name was too long 😅). Use the _hide whitespace_ option when viewing the changes to see the added line by itself.
I've haven't rebased the branch on the latest, not sure what the preference is for this repo. Looking at history, it looks like merges are pretty common. Let me know if you want this rebased before merging.
Thanks for the review! 🙏

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
The last time I looked at this all CI jobs were failing to run at all and I couldn't figure it out. That seems to have been an upstream issue because everything I've poked recently has run fine.

**Pull request merged**
