### PR TITLE
Fix fenced code block syntax highlighting

### PR DESCRIPTION
**Pull request by ANK-dev**
* added support for tilde `~` fenced code blocks
* added support for arbitrary length code block fences

### CODE REVIEW

**Comment by ANK-dev** [comment]
As per [CommomMark Spec](https://spec.commonmark.org/0.29/#fenced-code-blocks), fenced code blocks can be written using either 3 or more `` ` `` or 3 or more `~`. Although the plugin successfully recognized backtick and tilde fenced code blocks, it only applied syntax highlighting for backtick fenced code blocks.

This pull request fixes this behavior, and also allows the code block fences themselves to be of an arbitrary length while maintaining syntax highlighting.

**Review by alerque — CHANGES_REQUESTED** [review]
I preliminary review of this looks solid to me. Would you by chance be around to either rebase on master or merge from master and resolve the merge conflicts?

**Comment by ANK-dev** [comment]
Just merged it. Can you check if it's ok?

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
Thanks for the contribution!

**Pull request merged**
